name: 插件列表验证

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: 安装依赖
      run: python -m pip install pydantic

    - name: 运行验证
      run: python scripts/validate_plugin_list.py